export const tagMap = {
  guofeng: '国风',
  qingfengmingyue: '清风明月',
  zitenghua: '紫藤花（紫色主题）',
  luoli: '萝莉',
  qinghuaci: '青花瓷',
  menghuan: '梦幻',
  wangjiaokamen: '旺角卡门',
  hanshizhengjianzhao: '韩式证件照',
  chunyu: '纯欲',
  hongmeigui: '红玫瑰',
  miaozu: '苗族',
  yonglanfeng: '慵懒风',
  shengri: '生日',
  huoli: '活力',
  he: '荷',
  qingpingguo: '青苹果',
  yundongshaonu: '运动少女',
  minguo: '民国',
  zhuyun: '竹韵',
  xiarieshenzhen: '夏日写真',
  heben: '赫本',
  dunhuangfeng: '敦煌风',
  fenweijiaopian: '氛围胶片感',
  jiangnanyanyu: '江南烟雨',
  luolita: '洛丽塔',
  balei: '芭蕾',
  zangzu: '藏族',
  meishifugu: '美式复古',
  ccd: 'ccd',
  lvyexianzong: '绿野仙踪',
  rijiepian: '日系胶片感',
  qingyangshaonu: '轻氧少女',
  zaitaogongzhu: '在逃公主',
  qingsechulian: '青涩初恋',
  pishuai: '痞帅',
  huabanshaonian: '滑板少年',
  guofengshaonian: '国风少年',
};
export const tags = [
  '国风',
  '清风明月',
  '紫藤花（紫色主题）',
  '萝莉',
  '青花瓷',
  '梦幻',
  '旺角卡门',
  '韩式证件照',
  '纯欲',
  '红玫瑰',
  '苗族',
  '慵懒风',
  '生日',
  '活力',
  '荷',
  '青苹果',
  '运动少女',
  '民国',
  '竹韵',
  '夏日写真',
  '赫本',
  '敦煌风',
  '氛围胶片感',
  '江南烟雨',
  '洛丽塔',
  '芭蕾',
  '藏族',
  '美式复古',
  'ccd',
  '绿野仙踪',
  '日系胶片感',
  '轻氧少女',
  '在逃公主',
  '青涩初恋',
  '痞帅',
  '滑板少年',
  '国风少年',
];

const description =
  '请选择一张人脸清晰的照片，生成图片需要等待一段时间，可在作品页查看生成作品和进度，作品将在12小时后删除，请及时保存图片';
